force-app/main/default/objects/Personal__c/Personal__c.object-meta.xml
<CustomObject>
    <label>Personal</label>
    <nameField>
        <label>Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Personal__c/fields/Apellido__c.field-meta.xml
<CustomField>
    <fullName>Apellido__c</fullName>
    <label>Apellido</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Personal__c/fields/Nombre_cliente__c.field-meta.xml
<CustomField>
    <fullName>Nombre_cliente__c</fullName>
    <label>Nombre cliente</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/pdfprueba.cls
    public with sharing class pdfprueba {
        @AuraEnabled(cacheable=true)
        public static list<Personal__c> getbiblio(Integer searchText){
              //String linkValue = '%' + searchText + '%';
              //String linkValue = '%1212566%';

             // System.debug(linkValue);
            
            // Retorna los datos encontrados en el objeto Personal__c
            return[
               // SELECT Name, Apellido__c, Celular__c FROM Personal__c WHERE Name LIKE :linkValue
               SELECT Name, Nombre_cliente__c, Apellido__c FROM Personal__c WHERE Cedula__c =:searchText
            ]
            ;
            }
    }